spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 99b03667e9a08d23cb9ed98e09531d92
            client-secret: diRVTlruAgpzpMTX5GZs6aBHg0coLmQX
            redirect-uri: "http://localhost:8090/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email, talk_message

        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id